sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest PHP_REDIS=enabled
    - php: 5.6
      env: WP_VERSION=latest PHP_REDIS=enabled
    - php: 5.6
      env: WP_VERSION=latest PHP_REDIS=disabled
    - php: 5.6
      env: WP_VERSION=nightly PHP_REDIS=enabled

services:
    - redis-server

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
    - |
      if [[ "$PHP_REDIS" == "enabled" ]] ; then
        echo 'extension = "redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      fi
      phpunit
